### ISSUE TITLE
tracking manga

### ISSUE THREAD

**Issue by niksoc** [nyczbrandon/Mimi#2]
I think the automatic update to mal is a bit problematic because if I just open a random page in a manga to look at the art or something it gets added to mal. And then I have to go to mal and remove the entry. Maybe an option to start tracking a manga? In detail, if you start tracking a manga, mal and bookmarks will be updated and so on. If you stop tracking the manga, the bookmark will be deleted and mal manga status will change to dropped. I can work on it if you give me the go ahead.
Also I don't know if downloading the user's manga list for every page is efficient, but this is a performance issue and can be handled later. edit: nvm, I see that that's not the case.

**Comment by nyczbrandon** [comment]
Do you mean that there should be something like a button that can press to start or stop tracking?  I have a solution in mind for the problem of adding random manga when just browsing and am working on it now.

**Comment by niksoc** [comment]
yeah, similar to the chrome popup that asks if you want to save your password on this site ( to start tracking ).
To stop tracking, there will be a button next to the bookmark of each manga ( "drop") which will drop the manga in mal and the bookmarks and stop tracking it. What's your solution?

**Comment by nyczbrandon** [comment]
Oh that's what you meant by tracking. I thought you meant like you could be logged in and have it not update your mal unless the tracking function is turned on.
My solution to the issue is that when it finds a new manga that is not on your mal I will display a notification asking you if you want to add the manga to your list.  I am still not sure if I only want to ask if a manga is found on myanimelist or display what the search mal function returns which would be a punch of results and allow the user to choose which one to add.

**Comment by niksoc** [comment]
Ah that's the same thing then. I think it's undesirable to show a bunch of results (because it shows the lack of capability on the app's part to find the manga on mal and gives extra burden to the user) , it should only be done if a manga can't be found. 
P.S - can you write a function to update a manga's status to dropped on mal (the ajax request)? Then I can use it to add the drop functionality.

**Comment by nyczbrandon** [comment]
Yeah I can add that but first I think I need to change how everything works before that because to remove a manga you need to have the id of the manga which can be obtained by getting the name of the manga, but each reader has a different way of obtaining the info so making a delete function won't really work unless I somehow save the manga name.  That's why I think I am going to make a prototype that holds the functions as well as the manga name and other stuff so that can be possible.
